import { StyleSheet } from 'react-native';
import { hp, wp } from '../helpers/common';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F8FAFF",
  },
  mapHeader: {
    height: hp(33),
  },
  mapBackground: {
    flex: 1,
  },
  searchBarContainer: {
    flexDirection: "row",
    paddingHorizontal: wp(5),
    paddingTop: hp(4.5),
    alignItems: "center",
  },
  searchInput: {
    flex: 1,
    backgroundColor: "white",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 30,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginRight: 12,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 8,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchPlaceholder: {
    color: "#999",
    fontSize: 16,
  },
  notificationButton: {
    backgroundColor: "white",
    padding: 12,
    borderRadius: 30,
    shadowColor: "#000",
    shadowOpacity: 0.15,
    elevation: 8,
  },
  mainTitle: {
    fontSize: 38,
    fontWeight: "900",
    color: "#003087",
    marginLeft: wp(5),
    marginTop: hp(4),
    letterSpacing: 0.5,
  },
  createAccountButton: {
    backgroundColor: "white",
    alignSelf: "flex-start",
    marginLeft: wp(5),
    marginTop: hp(2),
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  createAccountText: {
    color: "#D32F2F",
    fontWeight: "700",
    fontSize: 16,
  },
  arrowIcon: {
    marginLeft: 8,
  },
  scrollContent: {
    paddingBottom: hp(5),
  },
  sectionTitle: {
    fontSize: 28,
    fontWeight: "800",
    color: "#003087",
    marginLeft: wp(5),
    marginTop: hp(4),
    marginBottom: hp(3),
  },
  servicesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: wp(5),
  },
  serviceCard: {
    width: wp(42),
    backgroundColor: "white",
    borderRadius: 20,
    paddingVertical: hp(4.5),
    alignItems: "center",
    marginBottom: hp(2.5),
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 10,
  },
  serviceTitle: {
    marginTop: 12,
    fontSize: 15,
    fontWeight: "600",
    color: "#003087",
    textAlign: "center",
  },
  bottomBanner: {
    marginHorizontal: wp(5),
    marginTop: hp(5),
    backgroundColor: "#003087",
    borderRadius: 24,
    paddingVertical: hp(6),
    paddingHorizontal: wp(6),
    alignItems: "center",
  },
  bannerTitle: {
    fontSize: 26,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
  },
  bannerSubtitle: {
    fontSize: 16,
    color: "#BBDEFB",
    textAlign: "center",
    marginTop: 12,
    lineHeight: 24,
  },
  signInButton: {
    marginTop: hp(3),
    backgroundColor: "white",
    paddingHorizontal: wp(25),
    paddingVertical: 16,
    borderRadius: 30,
  },
  signInText: {
    color: "#D32F2F",
    fontWeight: "bold",
    fontSize: 18,
  },
});

export default styles;
