export const recommendations = [
  // --- POBLACION 1 (Town Proper) ---
  { id: 1, title: 'St. Gregory the Great Parish Church', distance: 'Poblacion 1 • Historic Site', image: require('../assets/images/transportation/parishchrurch.png') },
  { id: 2, title: 'Tree Top Coffee Shop', distance: 'Poblacion 1 • Dining', image: require('../assets/images/transportation/treetop.png') },
  { id: 3, title: 'Jollibee Indang', distance: 'Poblacion 1 • Dining', image: require('../assets/images/transportation/jb.png') },
  { id: 4, title: '7-Eleven Indang', distance: 'Poblacion 1 • Convenience', image: require('../assets/images/transportation/711.png') },
  { id: 5, title: 'Indang Municipal Hall', distance: 'Poblacion 1 • Government', image: require('../assets/images/transportation/municipal.png') },
  { id: 6, title: 'Indang Town Plaza', distance: 'Poblacion 1 • Park' },
  { id: 7, title: 'PNP Indang Station', distance: 'Poblacion 1 • Service', image: require('../assets/images/transportation/pnp.png') },
  { id: 8, title: 'Indang Central Elem. School', distance: 'Poblacion 1 • Education' },
  { id: 9, title: 'Mercury Drug Indang', distance: 'Poblacion 1 • Pharmacy', image: require('../assets/images/transportation/mercury.png') },
  { id: 10, title: 'Bonifacio Monument', distance: 'Poblacion 1 • Landmark', image: require('../assets/images/transportation/bonifacioshrine.png') },

  // --- POBLACION 2 ---
  { id: 11, title: 'Indang Public Market', distance: 'Poblacion 2 • Market', image: require('../assets/images/transportation/pubmark.png') },
  { id: 12, title: 'Cup of Grace', distance: 'Poblacion 2 (San Gregorio) • Cafe', image: require('../assets/images/transportation/cog.png') },
  { id: 13, title: 'Drew\'s Brew & Bake', distance: 'Poblacion 2 (San Miguel) • Bakery', image: require('../assets/images/transportation/dbb.png') },
  { id: 14, title: 'Poblacion 2 Hall', distance: 'Poblacion 2 • Community' },
  { id: 15, title: 'Savemore Market', distance: 'Poblacion 2 • Grocery' },
  { id: 16, title: 'Indang Rural Health Unit', distance: 'Poblacion 2 • Health' },
  { id: 17, title: 'Alfamart Indang', distance: 'Poblacion 2 • Convenience', image: require('../assets/images/transportation/alfa.png') },
  { id: 18, title: 'Poblacion 2 Chapel', distance: 'Poblacion 2 • Religious' },
  { id: 19, title: 'Landbank Indang', distance: 'Poblacion 2 • Bank', image: require('../assets/images/transportation/landbank.png') },
  { id: 20, title: 'Old Water Tank', distance: 'Poblacion 2 • Landmark' },

  // --- POBLACION 3 ---
  { id: 21, title: 'Pio De Roda Cafe', distance: 'Poblacion 3 • Heritage Cafe', image: require('../assets/images/transportation/pio.png') },
  { id: 22, title: 'Coffee and Teacups', distance: 'Poblacion 3 (A. Mabini) • Cafe' },
  { id: 23, title: 'Klamulse Hotel', distance: 'Poblacion 3 • Hotel', image: require('../assets/images/transportation/klamulse.png') },
  { id: 24, title: 'Poblacion 3 Hall', distance: 'Poblacion 3 • Community' },
  { id: 25, title: 'St. Vincent Ferrer Chapel', distance: 'Poblacion 3 • Religious' },
  { id: 26, title: 'Bangko Mabuhay', distance: 'Poblacion 3 • Bank' },
  { id: 27, title: 'Poblacion 3 Bakery', distance: 'Poblacion 3 • Food' },
  { id: 28, title: 'Mhavis Clinic', distance: 'Poblacion 3 • Health', image: require('../assets/images/transportation/mhavis.png') },
  { id: 29, title: 'Poblacion 3 Court', distance: 'Poblacion 3 • Sports' },
  { id: 30, title: 'Ancestral House View', distance: 'Poblacion 3 • Historical' },

  // --- POBLACION 4 ---
  { id: 31, title: 'Cafe Hermano', distance: 'Poblacion 4 (Plaridel St) • Cafe', image: require('../assets/images/transportation/cafeherm.png') },
  { id: 32, title: 'Black Owl Cafe', distance: 'Poblacion 4 (Magtanggol St) • Cafe', image: require('../assets/images/transportation/blackowl.png') },
  { id: 33, title: 'The Port St. Café', distance: 'Poblacion 4 • Cafe', image: require('../assets/images/transportation/portst.png') },
  { id: 34, title: 'Poblacion 4 Hall', distance: 'Poblacion 4 • Community' },
  { id: 35, title: 'National High School', distance: 'Poblacion 4 • Education', image: require('../assets/images/transportation/inhs.png') },
  { id: 36, title: 'Poblacion 4 Chapel', distance: 'Poblacion 4 • Religious' },
  { id: 37, title: 'Indang Fire Station', distance: 'Poblacion 4 • Government' },
  { id: 38, title: 'Poblacion 4 Sports Complex', distance: 'Poblacion 4 • Sports' },
  { id: 39, title: 'Indang Post Office', distance: 'Poblacion 4 • Service' },
  { id: 40, title: 'Poblacion 4 Food Stalls', distance: 'Poblacion 4 • Dining' },

  // --- AGUS-US ---
  { id: 41, title: 'Terre Verte Farm Resort', distance: 'Brgy. Agus-us • Adventure Resort', image: require('../assets/images/transportation/terreverte.png') },
  { id: 42, title: 'La UlrichLand Farm Resort', distance: 'Brgy. Agus-us • Private Resort', image: require('../assets/images/transportation/laulrich.png') },
  { id: 43, title: 'Villa Soledad Garden Resort', distance: 'Brgy. Agus-us • Garden Resort', image: require('../assets/images/transportation/soledad.png') },
  { id: 44, title: 'Agus-us River Rapids', distance: 'Brgy. Agus-us • Nature' },
  { id: 45, title: 'Agus-us Hanging Bridge', distance: 'Brgy. Agus-us • Landmark' },
  { id: 46, title: 'Agus-us Barangay Hall', distance: 'Brgy. Agus-us • Community' },
  { id: 47, title: 'Agus-us Chapel', distance: 'Brgy. Agus-us • Religious' },
  { id: 48, title: 'Agus-us Elementary School', distance: 'Brgy. Agus-us • Education' },
  { id: 49, title: 'Agus-us Forest Trail', distance: 'Brgy. Agus-us • Hiking' },
  { id: 50, title: 'Agus-us View Deck', distance: 'Brgy. Agus-us • Scenic' },

  // --- ALULOD ---
  { id: 51, title: 'Villa Feliciana Farm & Resort', distance: 'Brgy. Alulod • Hotel/Resort', image: require('../assets/images/transportation/feliciana.png') },
  { id: 52, title: 'TOPSIDE CAFE', distance: 'Brgy. Alulod • Cafe', image: require('../assets/images/transportation/topside.png') },
  { id: 53, title: 'Kape-Fied', distance: 'Brgy. Alulod • Coffee Shop', image: require('../assets/images/transportation/kapefied.png') },
  { id: 54, title: 'Alulod River Crossing', distance: 'Brgy. Alulod • Nature' },
  { id: 55, title: 'San Isidro Labrador Chapel', distance: 'Brgy. Alulod • Religious' },
  { id: 56, title: 'Alulod Barangay Hall', distance: 'Brgy. Alulod • Community' },
  { id: 57, title: 'Alulod Covered Court', distance: 'Brgy. Alulod • Sports' },
  { id: 58, title: 'Alulod Bridge Landmark', distance: 'Brgy. Alulod • Landmark' },
  { id: 59, title: 'Alulod Flower Garden', distance: 'Brgy. Alulod • Nature' },
  { id: 60, title: 'Alulod Picnic Grounds', distance: 'Brgy. Alulod • Recreation' },

  // --- BANABA CERCA ---
  { id: 61, title: 'California Breeze Campsite', distance: 'Brgy. Banaba Cerca • Glamping', image: require('../assets/images/transportation/california.png') },
  { id: 62, title: 'CMJ Private Resort', distance: 'Brgy. Banaba Cerca • Private Villa', image: require('../assets/images/transportation/cmj.png') },
  { id: 63, title: 'Casita de Señerez Resort', distance: 'Brgy. Banaba Cerca • Family Resort', image: require('../assets/images/transportation/casita.png') },
  { id: 64, title: '143 Private Resort', distance: 'Brgy. Banaba Cerca • Resort' },
  { id: 65, title: 'Banaba Cerca Hall', distance: 'Brgy. Banaba Cerca • Community' },
  { id: 66, title: 'Banaba Cerca Chapel', distance: 'Brgy. Banaba Cerca • Religious' },
  { id: 67, title: 'Banaba Cerca Sports Complex', distance: 'Brgy. Banaba Cerca • Sports' },
  { id: 68, title: 'Banaba Cerca School', distance: 'Brgy. Banaba Cerca • Education' },
  { id: 69, title: 'Banaba Cerca Trail', distance: 'Brgy. Banaba Cerca • Adventure' },
  { id: 70, title: 'Banaba Cerca Arch', distance: 'Brgy. Banaba Cerca • Landmark' },

  // --- BANABA LEJOS ---
  { id: 71, title: 'Banaba Lejos River Stream', distance: 'Brgy. Banaba Lejos • Nature' },
  { id: 72, title: 'Banaba Lejos Farm', distance: 'Brgy. Banaba Lejos • Agri' },
  { id: 73, title: 'Banaba Lejos Chapel', distance: 'Brgy. Banaba Lejos • Religious' },
  { id: 74, title: 'Banaba Lejos Hall', distance: 'Brgy. Banaba Lejos • Community' },
  { id: 75, title: 'Banaba Lejos School', distance: 'Brgy. Banaba Lejos • Education' },
  { id: 76, title: 'Banaba Lejos Nature Trail', distance: 'Brgy. Banaba Lejos • Hiking' },
  { id: 77, title: 'Banaba Lejos Bamboo Grove', distance: 'Brgy. Banaba Lejos • Nature' },
  { id: 78, title: 'Banaba Lejos Basketball Court', distance: 'Brgy. Banaba Lejos • Sports' },
  { id: 79, title: 'Banaba Lejos Hanging Bridge', distance: 'Brgy. Banaba Lejos • Landmark' },
  { id: 80, title: 'Banaba Lejos Viewpoint', distance: 'Brgy. Banaba Lejos • Scenic' },

  // --- BANCOD ---
  { id: 81, title: 'Cavite State University (Main)', distance: 'Brgy. Bancod • Landmark', image: require('../assets/images/transportation/cvsu.png') },
  { id: 82, title: 'Tree Top Coffee Shop', distance: 'Brgy. Bancod • Restaurant', image: require('../assets/images/transportation/treetop.png') },
  { id: 83, title: 'Mango Tango Cafe', distance: 'Brgy. Bancod • Cafe', image: require('../assets/images/transportation/mangot.png') },
  { id: 84, title: 'Bancod River Resort', distance: 'Brgy. Bancod • Swimming' },
  { id: 85, title: 'CvSU Oval & Park', distance: 'Brgy. Bancod • Recreation' },
  { id: 86, title: 'Bancod Chapel', distance: 'Brgy. Bancod • Religious' },
  { id: 87, title: 'Bancod Barangay Hall', distance: 'Brgy. Bancod • Community' },
  { id: 88, title: 'Student Dormitories Area', distance: 'Brgy. Bancod • Housing' },
  { id: 89, title: 'Bancod Bridge', distance: 'Brgy. Bancod • Landmark' },
  { id: 90, title: 'Bancod Food Strip', distance: 'Brgy. Bancod • Dining' },

  // --- BUNA CERCA ---
  { id: 91, title: 'Harvest Kitchen & Cafe', distance: 'Brgy. Buna Cerca • Farm Cafe', image: require('../assets/images/transportation/bountyharv.png') },
  { id: 92, title: 'The Canopy Farm PH', distance: 'Brgy. Buna Cerca • Glamping/Farm', image: require('../assets/images/transportation/canopy.png') },
  { id: 93, title: 'Precious Garden Events Place', distance: 'Brgy. Buna Cerca • Events/Resort', image: require('../assets/images/transportation/precious.png') },
  { id: 94, title: 'Buna Cerca Waterfalls Access', distance: 'Brgy. Buna Cerca • Nature' },
  { id: 95, title: 'Buna Cerca Chapel', distance: 'Brgy. Buna Cerca • Religious' },
  { id: 96, title: 'Buna Cerca Hall', distance: 'Brgy. Buna Cerca • Community' },
  { id: 97, title: 'Buna Cerca School', distance: 'Brgy. Buna Cerca • Education' },
  { id: 98, title: 'Buna Cerca Sports Court', distance: 'Brgy. Buna Cerca • Sports' },
  { id: 99, title: 'Buna Cerca Health Center', distance: 'Brgy. Buna Cerca • Health' },
  { id: 100, title: 'Buna Cerca Bridge', distance: 'Brgy. Buna Cerca • Landmark' },

  // --- BUNA LEJOS I (UPDATED) ---
  { id: 101, title: 'Barrio Lejos Grill & Resto', distance: 'Brgy. Buna Lejos I • Dining' },
  { id: 102, title: 'Tazza Miha Cafe', distance: 'Brgy. Buna Lejos I • Cafe', image: require('../assets/images/transportation/tazzamiha.png') },
  { id: 103, title: 'Little HQ Cafe (Kalikhasan)', distance: 'Brgy. Buna Lejos I • Cafe', image: require('../assets/images/transportation/littlehq.png') },
  { id: 104, title: 'Buna Lejos I River', distance: 'Brgy. Buna Lejos I • Nature' },
  { id: 105, title: 'Buna Lejos I Chapel', distance: 'Brgy. Buna Lejos I • Religious' },
  { id: 106, title: 'Buna Lejos I Hall', distance: 'Brgy. Buna Lejos I • Community' },
  { id: 107, title: 'Buna Lejos I School', distance: 'Brgy. Buna Lejos I • Education' },
  { id: 108, title: 'Buna Lejos I Basketball Court', distance: 'Brgy. Buna Lejos I • Sports' },
  { id: 109, title: 'Buna Lejos I Arch', distance: 'Brgy. Buna Lejos I • Landmark' },
  { id: 110, title: 'Buna Lejos I View Deck', distance: 'Brgy. Buna Lejos I • Scenic' },

  // --- BUNA LEJOS II (UPDATED) ---
  { id: 111, title: 'Tagpuan Café', distance: 'Brgy. Buna Lejos II • Cafe' },
  { id: 112, title: 'Buna Lejos II Forest Patch', distance: 'Brgy. Buna Lejos II • Nature' },
  { id: 113, title: 'Buna Lejos II Chapel', distance: 'Brgy. Buna Lejos II • Religious' },
  { id: 114, title: 'Buna Lejos II Hall', distance: 'Brgy. Buna Lejos II • Community' },
  { id: 115, title: 'Buna Lejos II School', distance: 'Brgy. Buna Lejos II • Education' },
  { id: 116, title: 'Buna Lejos II Covered Court', distance: 'Brgy. Buna Lejos II • Sports' },
  { id: 117, title: 'Buna Lejos II River', distance: 'Brgy. Buna Lejos II • Nature' },
  { id: 118, title: 'Buna Lejos II Farm', distance: 'Brgy. Buna Lejos II • Agri' },
  { id: 119, title: 'Buna Lejos II Bridge', distance: 'Brgy. Buna Lejos II • Landmark' },
  { id: 120, title: 'Buna Lejos II Picnic Area', distance: 'Brgy. Buna Lejos II • Recreation' },

  // --- CALUMPANG CERCA ---
  { id: 121, title: 'Balay Indang', distance: 'Brgy. Calumpang Cerca • Bed & Breakfast', image: require('../assets/images/transportation/balay.png') },
  { id: 122, title: 'Calumpang Cerca Fields', distance: 'Brgy. Calumpang Cerca • Nature' },
  { id: 123, title: 'Calumpang Cerca Chapel', distance: 'Brgy. Calumpang Cerca • Religious' },
  { id: 124, title: 'Calumpang Cerca Hall', distance: 'Brgy. Calumpang Cerca • Community' },
  { id: 125, title: 'Calumpang Cerca School', distance: 'Brgy. Calumpang Cerca • Education' },
  { id: 126, title: 'Calumpang Cerca Court', distance: 'Brgy. Calumpang Cerca • Sports' },
  { id: 127, title: 'Calumpang Cerca Clinic', distance: 'Brgy. Calumpang Cerca • Health' },
  { id: 128, title: 'Calumpang Cerca Gardens', distance: 'Brgy. Calumpang Cerca • Nature' },
  { id: 129, title: 'Calumpang Cerca Landmark', distance: 'Brgy. Calumpang Cerca • Landmark' },
  { id: 130, title: 'Calumpang Cerca View', distance: 'Brgy. Calumpang Cerca • Scenic' },

  // --- CALUMPANG LEJOS I ---
  { id: 131, title: 'Calumpang Lejos River', distance: 'Brgy. Calumpang Lejos • Nature' },
  { id: 132, title: 'Calumpang Lejos Farm', distance: 'Brgy. Calumpang Lejos • Agri' },
  { id: 133, title: 'Calumpang Lejos Chapel', distance: 'Brgy. Calumpang Lejos • Religious' },
  { id: 134, title: 'Calumpang Lejos Hall', distance: 'Brgy. Calumpang Lejos • Community' },
  { id: 135, title: 'Calumpang Lejos School', distance: 'Brgy. Calumpang Lejos • Education' },
  { id: 136, title: 'Calumpang Lejos Court', distance: 'Brgy. Calumpang Lejos • Sports' },
  { id: 137, title: 'Calumpang Lejos Bridge', distance: 'Brgy. Calumpang Lejos • Landmark' },
  { id: 138, title: 'Calumpang Lejos Trails', distance: 'Brgy. Calumpang Lejos • Hiking' },
  { id: 139, title: 'Calumpang Lejos Spring', distance: 'Brgy. Calumpang Lejos • Nature' },
  { id: 140, title: 'Calumpang Lejos View', distance: 'Brgy. Calumpang Lejos • Scenic' },

  // --- CARASUCHI (UPDATED) ---
  { id: 141, title: 'The Ravine by One Selah', distance: 'Brgy. Carasuchi • Resort', image: require('../assets/images/transportation/ravine.png') },
  { id: 142, title: 'Carasuchi Villa Garden', distance: 'Brgy. Carasuchi • Private Villa' },
  { id: 143, title: 'Milani\'s Bed & Breakfast', distance: 'Brgy. Carasuchi • B&B' },
  { id: 144, title: 'Casita Anahaw', distance: 'Brgy. Carasuchi • Vacation Rental', image: require('../assets/images/transportation/anahaw.png') },
  { id: 145, title: 'Carasuchi Villa Resort', distance: 'Brgy. Carasuchi • Swimming' },
  { id: 146, title: 'Carasuchi Chapel', distance: 'Brgy. Carasuchi • Religious' },
  { id: 147, title: 'Carasuchi Hall', distance: 'Brgy. Carasuchi • Community' },
  { id: 148, title: 'Carasuchi School', distance: 'Brgy. Carasuchi • Education' },
  { id: 149, title: 'Carasuchi Spring', distance: 'Brgy. Carasuchi • Nature' },
  { id: 150, title: 'Carasuchi Bridge', distance: 'Brgy. Carasuchi • Landmark' },

  // --- DAINE I ---
  { id: 151, title: 'Kaffi Lulu', distance: 'Brgy. Daine I • Coffee Shop' },
  { id: 152, title: 'Daine I Rice Terraces', distance: 'Brgy. Daine I • Scenic' },
  { id: 153, title: 'Daine I Chapel', distance: 'Brgy. Daine I • Religious' },
  { id: 154, title: 'Daine I Hall', distance: 'Brgy. Daine I • Community' },
  { id: 155, title: 'Daine I School', distance: 'Brgy. Daine I • Education' },
  { id: 156, title: 'Daine I Sports Center', distance: 'Brgy. Daine I • Sports' },
  { id: 157, title: 'Daine I Garden', distance: 'Brgy. Daine I • Nature' },
  { id: 158, title: 'Daine I Health Center', distance: 'Brgy. Daine I • Health' },
  { id: 159, title: 'Daine I Landmark Arch', distance: 'Brgy. Daine I • Landmark' },
  { id: 160, title: 'Daine I River Access', distance: 'Brgy. Daine I • Nature' },

  // --- DAINE II ---
  { id: 161, title: 'Daine II Farm View', distance: 'Brgy. Daine II • Scenic' },
  { id: 162, title: 'Daine II River Stream', distance: 'Brgy. Daine II • Nature' },
  { id: 163, title: 'Daine II Chapel', distance: 'Brgy. Daine II • Religious' },
  { id: 164, title: 'Daine II Hall', distance: 'Brgy. Daine II • Community' },
  { id: 165, title: 'Daine II School Annex', distance: 'Brgy. Daine II • Education' },
  { id: 166, title: 'Daine II Basketball Court', distance: 'Brgy. Daine II • Sports' },
  { id: 167, title: 'Daine II Viewpoint', distance: 'Brgy. Daine II • Scenic' },
  { id: 168, title: 'Daine II Clinic', distance: 'Brgy. Daine II • Health' },
  { id: 169, title: 'Daine II Bridge', distance: 'Brgy. Daine II • Landmark' },
  { id: 170, title: 'Daine II Trails', distance: 'Brgy. Daine II • Hiking' },

  // --- GUYAM MALAKI ---
  { id: 171, title: 'Guyam Malaki Falls', distance: 'Brgy. Guyam Malaki • Nature' },
  { id: 172, title: 'Guyam Malaki River', distance: 'Brgy. Guyam Malaki • Scenic' },
  { id: 173, title: 'Guyam Malaki Farm', distance: 'Brgy. Guyam Malaki • Agri' },
  { id: 174, title: 'Guyam Malaki Chapel', distance: 'Brgy. Guyam Malaki • Religious' },
  { id: 175, title: 'Guyam Malaki Hall', distance: 'Brgy. Guyam Malaki • Community' },
  { id: 176, title: 'Guyam Malaki School', distance: 'Brgy. Guyam Malaki • Education' },
  { id: 177, title: 'Guyam Malaki Court', distance: 'Brgy. Guyam Malaki • Sports' },
  { id: 178, title: 'Guyam Malaki Trails', distance: 'Brgy. Guyam Malaki • Adventure' },
  { id: 179, title: 'Guyam Malaki Arch', distance: 'Brgy. Guyam Malaki • Landmark' },
  { id: 180, title: 'Guyam Malaki View Deck', distance: 'Brgy. Guyam Malaki • Scenic' },

  // --- GUYAM MUNTI ---
  { id: 181, title: 'Guyam Munti Nature View', distance: 'Brgy. Guyam Munti • Nature' },
  { id: 182, title: 'Guyam Munti Spring', distance: 'Brgy. Guyam Munti • Water' },
  { id: 183, title: 'Guyam Munti Chapel', distance: 'Brgy. Guyam Munti • Religious' },
  { id: 184, title: 'Guyam Munti Hall', distance: 'Brgy. Guyam Munti • Community' },
  { id: 185, title: 'Guyam Munti School', distance: 'Brgy. Guyam Munti • Education' },
  { id: 186, title: 'Guyam Munti Court', distance: 'Brgy. Guyam Munti • Sports' },
  { id: 187, title: 'Guyam Munti Farm', distance: 'Brgy. Guyam Munti • Agri' },
  { id: 188, title: 'Guyam Munti Bridge', distance: 'Brgy. Guyam Munti • Landmark' },
  { id: 189, title: 'Guyam Munti Picnic Spot', distance: 'Brgy. Guyam Munti • Recreation' },
  { id: 190, title: 'Guyam Munti Trail', distance: 'Brgy. Guyam Munti • Walk' },

  // --- HARASAN ---
  { id: 191, title: 'Harasan Bamboo Grove', distance: 'Brgy. Harasan • Nature' },
  { id: 192, title: 'Harasan River Crossing', distance: 'Brgy. Harasan • Adventure' },
  { id: 193, title: 'Harasan Fruit Farm', distance: 'Brgy. Harasan • Agri' },
  { id: 194, title: 'Harasan Chapel', distance: 'Brgy. Harasan • Religious' },
  { id: 195, title: 'Harasan Hall', distance: 'Brgy. Harasan • Community' },
  { id: 196, title: 'Harasan School', distance: 'Brgy. Harasan • Education' },
  { id: 197, title: 'Harasan Sports Court', distance: 'Brgy. Harasan • Sports' },
  { id: 198, title: 'Harasan Multi-Purpose Hall', distance: 'Brgy. Harasan • Event' },
  { id: 199, title: 'Harasan Landmark Arch', distance: 'Brgy. Harasan • Landmark' },
  { id: 200, title: 'Harasan Viewpoint', distance: 'Brgy. Harasan • Scenic' },

  // --- KAYQUIT I (UPDATED) ---
  { id: 201, title: 'Kape-Fied', distance: 'Brgy. Kayquit I • Cafe', image: require('../assets/images/transportation/kapefied.png') },
  { id: 202, title: 'Bistro Gorda', distance: 'Brgy. Kayquit I • Brunch/Dining' },
  { id: 203, title: 'Patio Buendia', distance: 'Brgy. Kayquit I • Events', image: require('../assets/images/transportation/buendia.png') },
  { id: 204, title: 'Kayquit I Sports Complex', distance: 'Brgy. Kayquit I • Sports' },
  { id: 205, title: 'Kayquit I Chapel', distance: 'Brgy. Kayquit I • Religious' },
  { id: 206, title: 'Kayquit I Hall', distance: 'Brgy. Kayquit I • Community' },
  { id: 207, title: 'Kayquit I School', distance: 'Brgy. Kayquit I • Education' },
  { id: 208, title: 'Kayquit I Clinic', distance: 'Brgy. Kayquit I • Health' },
  { id: 209, title: 'Kayquit I Arch', distance: 'Brgy. Kayquit I • Landmark' },
  { id: 210, title: 'Kayquit I View', distance: 'Brgy. Kayquit I • Scenic' },

  // --- KAYQUIT II (UPDATED) ---
  { id: 211, title: 'La Casa Cita', distance: 'Brgy. Kayquit II • Homestay', image: require('../assets/images/transportation/lacasasita.png') },
  { id: 212, title: 'Kayquit II Resort', distance: 'Brgy. Kayquit II • Swimming' },
  { id: 213, title: 'Kayquit II Farm', distance: 'Brgy. Kayquit II • Agri' },
  { id: 214, title: 'Kayquit II Chapel', distance: 'Brgy. Kayquit II • Religious' },
  { id: 215, title: 'Kayquit II Hall', distance: 'Brgy. Kayquit II • Community' },
  { id: 216, title: 'Kayquit II School', distance: 'Brgy. Kayquit II • Education' },
  { id: 217, title: 'Kayquit II Court', distance: 'Brgy. Kayquit II • Sports' },
  { id: 218, title: 'Kayquit II Bridge', distance: 'Brgy. Kayquit II • Landmark' },
  { id: 219, title: 'Kayquit II Trail', distance: 'Brgy. Kayquit II • Adventure' },
  { id: 220, title: 'Kayquit II River View', distance: 'Brgy. Kayquit II • Scenic' },

  // --- KAYQUIT III (UPDATED) ---
  { id: 221, title: 'Siglo Farm Cafe', distance: 'Brgy. Kayquit III • Farm Cafe', image: require('../assets/images/transportation/siglo.png') },
  { id: 222, title: 'Siglo Paraiso Farm Resort', distance: 'Brgy. Kayquit III • Resort', image: require('../assets/images/transportation/paraiso.png') },
  { id: 223, title: 'Soiree Events Place', distance: 'Brgy. Kayquit III • Events', image: require('../assets/images/transportation/soiree.png') },
  { id: 224, title: 'Paraiso Farm Resort', distance: 'Brgy. Kayquit III • Resort', image: require('../assets/images/transportation/paraiso.png') },
  { id: 225, title: 'Lopez Private Resort', distance: 'Brgy. Kayquit III • Resort', image: require('../assets/images/transportation/lopez.png') },
  { id: 226, title: 'Kayquit III Organic Farm', distance: 'Brgy. Kayquit III • Agri' },
  { id: 227, title: 'Kayquit III Chapel', distance: 'Brgy. Kayquit III • Religious' },
  { id: 228, title: 'Kayquit III Hall', distance: 'Brgy. Kayquit III • Community' },
  { id: 229, title: 'Kayquit III School', distance: 'Brgy. Kayquit III • Education' },
  { id: 230, title: 'Kayquit III Nature Park', distance: 'Brgy. Kayquit III • Nature' },

  // --- KAYTAMBOG ---
  { id: 231, title: 'Happy Habits Cafe', distance: 'Brgy. Kaytambog • Resort Cafe', image: require('../assets/images/transportation/happyhab.png') },
  { id: 232, title: 'Filomena Springs Nature Resort', distance: 'Brgy. Kaytambog • Resort', image: require('../assets/images/transportation/filomena.png') },
  { id: 233, title: 'Terrace Hill Resort', distance: 'Brgy. Kaytambog • Resort', image: require('../assets/images/transportation/terrace.png') },
  { id: 234, title: 'Kaytambog River', distance: 'Brgy. Kaytambog • Nature' },
  { id: 235, title: 'Kaytambog Picnic Area', distance: 'Brgy. Kaytambog • Recreation' },
  { id: 236, title: 'Kaytambog Chapel', distance: 'Brgy. Kaytambog • Religious' },
  { id: 237, title: 'Kaytambog Hall', distance: 'Brgy. Kaytambog • Community' },
  { id: 238, title: 'Kaytambog School', distance: 'Brgy. Kaytambog • Education' },
  { id: 239, title: 'Kaytambog Basketball Court', distance: 'Brgy. Kaytambog • Sports' },
  { id: 240, title: 'Kaytambog Bridge', distance: 'Brgy. Kaytambog • Landmark' },

  // --- KAYTAPOS ---
  { id: 241, title: 'Bari Cafe', distance: 'Brgy. Kaytapos • Coffee Shop', image: require('../assets/images/transportation/baricafe.png') },
  { id: 242, title: 'Palsahingin Falls', distance: 'Brgy. Kaytapos • Waterfalls', image: require('../assets/images/transportation/palsahingin.png') },
  { id: 243, title: 'Kaytapos River Trek', distance: 'Brgy. Kaytapos • Adventure' },
  { id: 244, title: 'Kaytapos Hanging Bridge', distance: 'Brgy. Kaytapos • Landmark' },
  { id: 245, title: 'Kaytapos Garden', distance: 'Brgy. Kaytapos • Nature' },
  { id: 246, title: 'Kaytapos Chapel', distance: 'Brgy. Kaytapos • Religious' },
  { id: 247, title: 'Kaytapos Hall', distance: 'Brgy. Kaytapos • Community' },
  { id: 248, title: 'Kaytapos School', distance: 'Brgy. Kaytapos • Education' },
  { id: 249, title: 'Kaytapos Court', distance: 'Brgy. Kaytapos • Sports' },
  { id: 250, title: 'Kaytapos Viewpoint', distance: 'Brgy. Kaytapos • Scenic' },

  // --- LIMBON ---
  { id: 251, title: 'Bonifacio Shrine', distance: 'Brgy. Limbon • Historical Landmark', image: require('../assets/images/transportation/bonifacioshrine.png') },
  { id: 252, title: 'Limbon River', distance: 'Brgy. Limbon • Nature' },
  { id: 253, title: 'Limbon Park', distance: 'Brgy. Limbon • Recreation' },
  { id: 254, title: 'Limbon Historical Marker', distance: 'Brgy. Limbon • Landmark' },
  { id: 255, title: 'Limbon Chapel', distance: 'Brgy. Limbon • Religious' },
  { id: 256, title: 'Limbon Hall', distance: 'Brgy. Limbon • Community' },
  { id: 257, title: 'Limbon School', distance: 'Brgy. Limbon • Education' },
  { id: 258, title: 'Limbon Court', distance: 'Brgy. Limbon • Sports' },
  { id: 259, title: 'Limbon Souvenir Shop', distance: 'Brgy. Limbon • Shopping' },
  { id: 260, title: 'Limbon Nature Trail', distance: 'Brgy. Limbon • Walking' },

  // --- LUMAMPONG BALAGBAG ---
  { id: 261, title: 'Lumampong Balagbag View', distance: 'Lumampong Balagbag • Scenic' },
  { id: 262, title: 'Lumampong Cave', distance: 'Lumampong Balagbag • Nature', image: require('../assets/images/transportation/lumampongcave.png') },
  { id: 263, title: 'Lumampong Balagbag Farm', distance: 'Lumampong Balagbag • Agri' },
  { id: 264, title: 'Lumampong Balagbag River', distance: 'Lumampong Balagbag • Nature' },
  { id: 265, title: 'Lumampong Balagbag Chapel', distance: 'Lumampong Balagbag • Religious' },
  { id: 266, title: 'Lumampong Balagbag Hall', distance: 'Lumampong Balagbag • Community' },
  { id: 267, title: 'Lumampong Balagbag School', distance: 'Lumampong Balagbag • Education' },
  { id: 268, title: 'Lumampong Balagbag Court', distance: 'Lumampong Balagbag • Sports' },
  { id: 269, title: 'Lumampong Balagbag Arch', distance: 'Lumampong Balagbag • Landmark' },
  { id: 270, title: 'Lumampong Balagbag Trail', distance: 'Lumampong Balagbag • Adventure' },

  // --- LUMAMPONG HALAYHAY ---
  { id: 271, title: 'Alta Rios Resort', distance: 'Lumampong Halayhay • Resort', image: require('../assets/images/transportation/altarios.png') },
  { id: 272, title: 'The Ravine by One Selah', distance: 'Lumampong Halayhay • Resort', image: require('../assets/images/transportation/ravine.png') },
  { id: 273, title: 'Lumampong Halayhay Garden', distance: 'Lumampong Halayhay • Nature' },
  { id: 274, title: 'Lumampong Halayhay Farm', distance: 'Lumampong Halayhay • Agri' },
  { id: 275, title: 'Lumampong Halayhay Chapel', distance: 'Lumampong Halayhay • Religious' },
  { id: 276, title: 'Lumampong Halayhay Hall', distance: 'Lumampong Halayhay • Community' },
  { id: 277, title: 'Lumampong Halayhay School', distance: 'Lumampong Halayhay • Education' },
  { id: 278, title: 'Lumampong Halayhay Court', distance: 'Lumampong Halayhay • Sports' },
  { id: 279, title: 'Lumampong Halayhay Bridge', distance: 'Lumampong Halayhay • Landmark' },
  { id: 280, title: 'Lumampong Halayhay Trail', distance: 'Lumampong Halayhay • Walk' },

  // --- MAHABANG KAHOY CERCA ---
  { id: 281, title: 'Cafe Juana', distance: 'Mahabang Kahoy Cerca • Coffee Shop', image: require('../assets/images/transportation/cafejuana.png') },
  { id: 282, title: 'Photograph Cafe', distance: 'Mahabang Kahoy Cerca • Coffee Shop' },
  { id: 283, title: 'Driftwoods Action Park', distance: 'Mahabang Kahoy Cerca • Adventure', image: require('../assets/images/transportation/driftwoods.png') },
  { id: 284, title: 'Mahabang Kahoy Cerca River', distance: 'Mahabang Kahoy Cerca • Nature' },
  { id: 285, title: 'Mahabang Kahoy Cerca View', distance: 'Mahabang Kahoy Cerca • Scenic' },
  { id: 286, title: 'Mahabang Kahoy Cerca Farm', distance: 'Mahabang Kahoy Cerca • Agri' },
  { id: 287, title: 'Mahabang Kahoy Cerca Chapel', distance: 'Mahabang Kahoy Cerca • Religious' },
  { id: 288, title: 'Mahabang Kahoy Cerca Hall', distance: 'Mahabang Kahoy Cerca • Community' },
  { id: 289, title: 'Mahabang Kahoy Cerca School', distance: 'Mahabang Kahoy Cerca • Education' },
  { id: 290, title: 'Mahabang Kahoy Cerca Court', distance: 'Mahabang Kahoy Cerca • Sports' },

  // --- MAHABANG KAHOY LEJOS ---
  { id: 291, title: 'A&A Garden Suites', distance: 'Mahabang Kahoy Lejos • Hotel' },
  { id: 292, title: 'Mahabang Kahoy Lejos Nature', distance: 'Mahabang Kahoy Lejos • Nature' },
  { id: 293, title: 'Mahabang Kahoy Lejos Farm', distance: 'Mahabang Kahoy Lejos • Agri' },
  { id: 294, title: 'Mahabang Kahoy Lejos View', distance: 'Mahabang Kahoy Lejos • Scenic' },
  { id: 295, title: 'Mahabang Kahoy Lejos Chapel', distance: 'Mahabang Kahoy Lejos • Religious' },
  { id: 296, title: 'Mahabang Kahoy Lejos Hall', distance: 'Mahabang Kahoy Lejos • Community' },
  { id: 297, title: 'Mahabang Kahoy Lejos School', distance: 'Mahabang Kahoy Lejos • Education' },
  { id: 298, title: 'Mahabang Kahoy Lejos Court', distance: 'Mahabang Kahoy Lejos • Sports' },
  { id: 299, title: 'Mahabang Kahoy Lejos Arch', distance: 'Mahabang Kahoy Lejos • Landmark' },
  { id: 300, title: 'Mahabang Kahoy Lejos Trail', distance: 'Mahabang Kahoy Lejos • Hiking' },

  // --- MATAAS NA LUPA ---
  { id: 301, title: 'The Farm Shack Resort', distance: 'Brgy. Mataas na Lupa • Resort', image: require('../assets/images/transportation/farmsahck.png') },
  { id: 302, title: 'Mataas na Lupa Ridge View', distance: 'Brgy. Mataas na Lupa • Scenic' },
  { id: 303, title: 'Mataas na Lupa Spring', distance: 'Brgy. Mataas na Lupa • Nature' },
  { id: 304, title: 'Mataas na Lupa Farm', distance: 'Brgy. Mataas na Lupa • Agri' },
  { id: 305, title: 'Mataas na Lupa Chapel', distance: 'Brgy. Mataas na Lupa • Religious' },
  { id: 306, title: 'Mataas na Lupa Hall', distance: 'Brgy. Mataas na Lupa • Community' },
  { id: 307, title: 'Mataas na Lupa School', distance: 'Brgy. Mataas na Lupa • Education' },
  { id: 308, title: 'Mataas na Lupa Court', distance: 'Brgy. Mataas na Lupa • Sports' },
  { id: 309, title: 'Mataas na Lupa Bridge', distance: 'Brgy. Mataas na Lupa • Landmark' },
  { id: 310, title: 'Mataas na Lupa Trails', distance: 'Brgy. Mataas na Lupa • Walk' },

  // --- PULO ---
  { id: 311, title: 'Pulo River Crossing', distance: 'Brgy. Pulo • Nature' },
  { id: 312, title: 'Pulo Agricultural Farm', distance: 'Brgy. Pulo • Agri' },
  { id: 313, title: 'Pulo View Deck', distance: 'Brgy. Pulo • Scenic' },
  { id: 314, title: 'Pulo Chapel', distance: 'Brgy. Pulo • Religious' },
  { id: 315, title: 'Pulo Barangay Hall', distance: 'Brgy. Pulo • Community' },
  { id: 316, title: 'Pulo Elementary School', distance: 'Brgy. Pulo • Education' },
  { id: 317, title: 'Pulo Basketball Court', distance: 'Brgy. Pulo • Sports' },
  { id: 318, title: 'Pulo Landmark Arch', distance: 'Brgy. Pulo • Landmark' },
  { id: 319, title: 'Pulo Nature Trail', distance: 'Brgy. Pulo • Walk' },
  { id: 320, title: 'Pulo Picnic Ground', distance: 'Brgy. Pulo • Recreation' },

  // --- TAMBO BALAGBAG ---
  { id: 321, title: 'Tambo Balagbag River', distance: 'Tambo Balagbag • Nature' },
  { id: 322, title: 'Tambo Balagbag Garden', distance: 'Tambo Balagbag • Nature' },
  { id: 323, title: 'Tambo Balagbag Farm', distance: 'Tambo Balagbag • Agri' },
  { id: 324, title: 'Tambo Balagbag View', distance: 'Tambo Balagbag • Scenic' },
  { id: 325, title: 'Tambo Balagbag Chapel', distance: 'Tambo Balagbag • Religious' },
  { id: 326, title: 'Tambo Balagbag Hall', distance: 'Tambo Balagbag • Community' },
  { id: 327, title: 'Tambo Balagbag School', distance: 'Tambo Balagbag • Education' },
  { id: 328, title: 'Tambo Balagbag Court', distance: 'Tambo Balagbag • Sports' },
  { id: 329, title: 'Tambo Balagbag Arch', distance: 'Tambo Balagbag • Landmark' },
  { id: 330, title: 'Tambo Balagbag Trail', distance: 'Tambo Balagbag • Adventure' },

  // --- TAMBO ILAYA ---
  { id: 331, title: 'Rmb\'s Downton Place', distance: 'Brgy. Tambo Ilaya • Cabin' },
  { id: 332, title: 'Tambo Ilaya River', distance: 'Brgy. Tambo Ilaya • Nature' },
  { id: 333, title: 'Tambo Ilaya Farm', distance: 'Brgy. Tambo Ilaya • Agri' },
  { id: 334, title: 'Tambo Ilaya View', distance: 'Brgy. Tambo Ilaya • Scenic' },
  { id: 335, title: 'Tambo Ilaya Chapel', distance: 'Brgy. Tambo Ilaya • Religious' },
  { id: 336, title: 'Tambo Ilaya Hall', distance: 'Brgy. Tambo Ilaya • Community' },
  { id: 337, title: 'Tambo Ilaya School', distance: 'Brgy. Tambo Ilaya • Education' },
  { id: 338, title: 'Tambo Ilaya Court', distance: 'Brgy. Tambo Ilaya • Sports' },
  { id: 339, title: 'Tambo Ilaya Bridge', distance: 'Brgy. Tambo Ilaya • Landmark' },
  { id: 340, title: 'Tambo Ilaya Trail', distance: 'Brgy. Tambo Ilaya • Walk' },

  // --- TAMBO KULIT ---
  { id: 341, title: 'Rio Villa Nuevo Resort', distance: 'Brgy. Tambo Kulit • Resort', image: require('../assets/images/transportation/rio.png') },
  { id: 342, title: 'Villa Colmenar Resort', distance: 'Brgy. Tambo Kulit • Swimming', image: require('../assets/images/transportation/colmenar.png') },
  { id: 343, title: 'Tambo Kulit Spring', distance: 'Brgy. Tambo Kulit • Nature' },
  { id: 344, title: 'Tambo Kulit Farm', distance: 'Brgy. Tambo Kulit • Agri' },
  { id: 345, title: 'Tambo Kulit View', distance: 'Brgy. Tambo Kulit • Scenic' },
  { id: 346, title: 'Tambo Kulit Chapel', distance: 'Brgy. Tambo Kulit • Religious' },
  { id: 347, title: 'Tambo Kulit Hall', distance: 'Brgy. Tambo Kulit • Community' },
  { id: 348, title: 'Tambo Kulit School', distance: 'Brgy. Tambo Kulit • Education' },
  { id: 349, title: 'Tambo Kulit Court', distance: 'Brgy. Tambo Kulit • Sports' },
  { id: 350, title: 'Tambo Kulit Bridge', distance: 'Brgy. Tambo Kulit • Landmark' },

  // --- TAMBO MALAKI ---
  { id: 351, title: 'EMV Flower Farm', distance: 'Brgy. Tambo Malaki • Agri-Tourism', image: require('../assets/images/transportation/emv.png') },
  { id: 352, title: 'Leaf & Brew Café', distance: 'Brgy. Tambo Malaki • Coffee Shop', image: require('../assets/images/transportation/leafnbrew.png') },
  { id: 353, title: 'Chillax Inn', distance: 'Brgy. Tambo Malaki • Inn', image: require('../assets/images/transportation/chillax.png') },
  { id: 354, title: 'Tambo Malaki River', distance: 'Brgy. Tambo Malaki • Nature' },
  { id: 355, title: 'Tambo Malaki View', distance: 'Brgy. Tambo Malaki • Scenic' },
  { id: 356, title: 'Tambo Malaki Chapel', distance: 'Brgy. Tambo Malaki • Religious' },
  { id: 357, title: 'Tambo Malaki Hall', distance: 'Brgy. Tambo Malaki • Community' },
  { id: 358, title: 'Tambo Malaki School', distance: 'Brgy. Tambo Malaki • Education' },
  { id: 359, title: 'Tambo Malaki Court', distance: 'Brgy. Tambo Malaki • Sports' },
  { id: 360, title: 'Tambo Malaki Bridge', distance: 'Brgy. Tambo Malaki • Landmark' },
];